### ISSUE TITLE
Link - Infinite download?

### ISSUE THREAD

**Issue by ericwood8** [Jinjinov/TheLastTime#1]
Your example page: https://ididit.today/ seems to be on infinite download today.
I know this worked at some point because I was impressed to keep a link to your code.

**Comment by ericwood8** [comment]
Closed issue.  Reclicked and link worked.

**Comment by Jinjinov** [comment]
@ericwood8 I am glad that you like it. Do you have any feedback? :)

**Comment by ericwood8** [comment]
I am not sure where in Github you like my feedback since it is not really an issue.
My Background: A career software developer that is expanding my learning about Blazor WebAssembly. I am planning to make a workplace LOB application with CRUD screens.
* Where your application stands out is the amount and variety to customization you can do with it.  
* I would say your biggest drawback is when a user first starts and their is no prior settings to load, all the settings to show things are turned off so they are invisible.  So as a result I did not know about all the cool features and customization settings I could set.  This problem is easily fixed by having the default to "show" rather than "not show".
* I like your page layout of the modal About / Examples / Help with their icons.  
* I wonder if you could change the category filtering button bar with "All", "No", "1", "2", etc.  to say the category name such as "Exercise" instead of "2".  But understand that the filtering button could have to change if I edited "Exercise" to be "Work Out".
* In your row data, I like your star and pin icons and understand their purpose.  The exclamation mark "!" I am less certain of its purpose because it looks same size and color and height as the star and pin buttons.  My guess is that "!" is for undefined percentages of time elapsed OR for reminder to do the activity.
* In your row data, I like the check mark button for doing an activity.  I like the category edit and delete buttons and understand their purpose.  I like your save and cancel when you edit a category name.
* Overall, an excellent application with outstanding customization.

**Comment by Jinjinov** [comment]
@ericwood8 Thank you for your very valuable feedback! I am also learning about Blazor.

- The default was "show" but then I got feedback that the app is too overwhelming. I must find a way to balance and better explain this.
- Renaming a category is not a problem, the problem with displaying the category name in the header is screen width on smaller devices (tablets, 15" laptops, ...). I was thinking to assign a different icon to each category and show the icon in the header, but the problem is where to get hundreds of custom icons that exactly match your custom category name.
- The exclamation mark means that the average time could not be computed because the habit was never done or done only once. You are right, the exclamation mark is never explained anywhere, thank you for noticing that :)

I am really glad you like it, it means a lot to me!
